# Generated by Django 6.0.5 on 2026-06-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courrier',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('traite', 'Traité'), ('archive', 'Archivé')], default='en_attente', max_length=20),
        ),
    ]
